#!/bin/sh
set -e
set -u

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  Archive items, ensuring the report action was used."
  curcmd=$(basename "$0")
  echo "    $curcmd \"THING TO DO\""
  echo ""
  exit
}


echo "Did you use report?"
read -r r
if [ "$r" = "y" ]; then
  $TODO_FULL_SH command archive
fi
