#!/bin/sh
set -e
set -u

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  List items sorted by date"
  curcmd=$(basename "$0")
  echo "    $curcmd \"THING TO DO\""
  echo ""
  exit
}


"$TODO_FULL_SH" -p command list -x "$@" | head -n -2 | IF=' ' awk '{t=$1;$1=$3;$3=$2;$2=t; print}' | sort -r
